name: Start Bot

on:
  schedule:
    - cron: '0 9 * * *'
      timezone: "Asia/Tehran"

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Start Railway Deployment
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.RAILWAY_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"query":"mutation { deploymentStart(id: \"4b28c15d-6362-4609-bfd6-d04c4d1f19c5\") }"}' \
            https://backboard.railway.com/graphql/v2
